language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
#install: 

# command to run tests
script:
  - python test.py

add_ons:
  sauce_connect: true

env:
  global:
  - secure mo+Ap7JO0SxyvTWnzbbwEsI+peFd0CZjKhADga3bbVoQtR9v/+dOJgRgukjMJRBQvEI9+Px1GSrVb7tK0Ull+4nGCnMxqXZSwatKl3x9X1YdZZKGA+ZPqp2DES/+UCDCi/gH3gcxZ9SPeaTe1Rbe4NA1u3Dxnc4KxiC4EfdvRQRVR6Eh1TcPwxe1YBtwLmnhyV0pf65SzN2qgus78cPt3JoQU+MoRmXIzw2K+UlS5PUoi8acqco/KAhI10c4pz1fpqoq2p2gi8kQgxrVNPh1KFoEWyih8LfW8b7TKBDI/8cNKVj/8PPKSlBACHUyyDrLD5LVaGNA5kkZLw6lsIEoZ6BKJi7/zqXJp7pMNoTde37bmctG+/ZrBne9SwLgGyd/oT3231/0sqMSs1CfPAzPGFQdTVDmgBGh5lWi90L9B5j+pq0efbBUT48pjppBMVY/nF+ga1qyBtrOp8r3avbW2CxqORDjezk1AAsHMFCQbsTxevodgkr01uhcxSubDKq8XcDd5NX1seHoEtVCgMtrrFezl7vJOesd7q0rd2GbjOmjj8ADKzcWW5yMoLC7S2kuaNawC0/pjLsaYFy1z+U+AvA6kvcmbMe0naX48WC/nCRGNK+S8IjZVsnMZvDusrjeEiBcsK0QbE06cGJ9VlCYcvGQwZ3aSNA9fVk6qhkG5+w=
  - secure b/o1JbXekg7nWOKv3f1lCBa+wBa3DP4voVLf0XNmRqVIWn3Fq2zgDndjfibViFd5CLB9z5vDTd2zNYH8v6YQTX0vG1tYDSXgLMn8+yC+Np36GR1GIuE5RWvfPExP/+CKTlEUofqHBxo1cHL9dDGWsvbkBU6EfEhsEJ921Aa3kVzZBB8inluBJWzis1cg4knlg5+GfimIk85A9RbnOwWmXQ/oEe+H5hCVAkfIEvUPfvdhI9f0Flqfr7tMGQNM7FAr6B4Abq/Sji0FR7EgQy/oHORvK6As912kaK6wpWe20u+KOWnCixw2ZbcI9sa4nBWppnMnufg0YSSy97euuiDMbkMfZjp6GNtppnZl0mcEPqIrumr5KJj7Nz/3TXqxeC9f59d08Qv5dCcBPBP4O6yqIuTMB0eL8vVlhsy1pAB8rtDD6LmC+KjzDXx1zcwYX4kA6VnfB/3gd/cvWyxXUmoO2oFmfldPzjUUlTcWeQW7Le1LXwfoPEdFnYqm/fCYlaAlaxQsZAcwmt1pOV3qhfCu+IrAHOgaO2AOpZE0bnKxaY6mrOZVj40+J2mXMeKCGDXbFI5Ga4Kk9qfQ7xyI/l8DYlLqs0YxqpV0oJcECWtQ1MZSioNJHkji7saKpNPlwKBzGLmzeFu8bLXfQwd0GFr/hRGuri3R1sasfvAwms2/hLo=